// <auto-generated />
using System;
using LightningOffer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LightningOffer.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210609141824_updatesaddemdum")]
    partial class updatesaddemdum
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LightningOffer.Models.Addendum", b =>
                {
                    b.Property<Guid>("Addendum_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Contingent_Addendum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Delayed_Possession_Addendum")
                        .HasColumnType("bit");

                    b.Property<bool>("HOA_Addendum")
                        .HasColumnType("bit");

                    b.Property<bool>("Other_Addendum")
                        .HasColumnType("bit");

                    b.HasKey("Addendum_id");

                    b.ToTable("Addendum");
                });

            modelBuilder.Entity("LightningOffer.Models.Appliance", b =>
                {
                    b.Property<Guid>("Appliance_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClothesDryer")
                        .HasColumnType("int");

                    b.Property<int>("ClothesWasher")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DishWasher")
                        .HasColumnType("int");

                    b.Property<int>("Microwave")
                        .HasColumnType("int");

                    b.Property<string>("Other")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Refrigerator")
                        .HasColumnType("int");

                    b.Property<int>("StoveRange")
                        .HasColumnType("int");

                    b.HasKey("Appliance_id");

                    b.ToTable("Appliance");
                });

            modelBuilder.Entity("LightningOffer.Models.Appraisal", b =>
                {
                    b.Property<Guid>("Appraisal_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Buyer_Appraisal_Required")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Lender_Appraisal_Required")
                        .HasColumnType("int");

                    b.Property<int>("No_Appraisal_Required")
                        .HasColumnType("int");

                    b.HasKey("Appraisal_id");

                    b.ToTable("Appraisal");
                });

            modelBuilder.Entity("LightningOffer.Models.Closing", b =>
                {
                    b.Property<Guid>("Closing_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active_Lease")
                        .HasColumnType("bit");

                    b.Property<bool>("Buyer_Title_Insurance")
                        .HasColumnType("bit");

                    b.Property<bool>("Closing_Window")
                        .HasColumnType("bit");

                    b.Property<bool>("Closing_Window_Latest")
                        .HasColumnType("bit");

                    b.Property<int>("Closing_Window_Soonest")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Keys_after_Closing")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Keys_at_Closing")
                        .HasColumnType("bit");

                    b.Property<string>("Other_Provisions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Specific_Closing_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Closing_id");

                    b.ToTable("Closing");
                });

            modelBuilder.Entity("LightningOffer.Models.Contract", b =>
                {
                    b.Property<Guid>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BuyerSignedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ListAgentSignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PurchasePrice")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SellerSignedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SellingAgentSignedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ContractId");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("LightningOffer.Models.Disclosure", b =>
                {
                    b.Property<Guid>("Disclosure_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Buyer_Waives_Lead_Paint_Inspection")
                        .HasColumnType("bit");

                    b.Property<bool>("Contingent_On_Lead_Paint")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Lead_Paint_Inspection_Window")
                        .HasColumnType("int");

                    b.Property<bool>("No_Lead_Paint")
                        .HasColumnType("bit");

                    b.Property<bool>("Seller_Disclosure_Recieved")
                        .HasColumnType("bit");

                    b.Property<int>("Seller_Lead_Paint_Response_Window")
                        .HasColumnType("int");

                    b.HasKey("Disclosure_id");

                    b.ToTable("Disclosure");
                });

            modelBuilder.Entity("LightningOffer.Models.Financial", b =>
                {
                    b.Property<Guid>("Financial_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ARM_Limits")
                        .HasColumnType("int");

                    b.Property<string>("Buyer_Loan_Application_Start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Cash")
                        .HasColumnType("bit");

                    b.Property<bool>("Conventional")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EMD")
                        .HasColumnType("int");

                    b.Property<bool>("EMD_With_ListingBroker")
                        .HasColumnType("bit");

                    b.Property<bool>("EMD_With_SellingBroker")
                        .HasColumnType("bit");

                    b.Property<bool>("FHA")
                        .HasColumnType("bit");

                    b.Property<bool>("Fixed_Rate")
                        .HasColumnType("bit");

                    b.Property<bool>("Gift")
                        .HasColumnType("bit");

                    b.Property<int>("Interest_Rate")
                        .HasColumnType("int");

                    b.Property<bool>("LineOfEquity")
                        .HasColumnType("bit");

                    b.Property<int>("Loan_Length")
                        .HasColumnType("int");

                    b.Property<bool>("Other_Financing")
                        .HasColumnType("bit");

                    b.Property<float>("Purchase_Price")
                        .HasColumnType("real");

                    b.Property<bool>("VA")
                        .HasColumnType("bit");

                    b.HasKey("Financial_id");

                    b.ToTable("Financial");
                });

            modelBuilder.Entity("LightningOffer.Models.FuelPropane", b =>
                {
                    b.Property<Guid>("FuelPropane_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Propane_Tank_Ownership")
                        .HasColumnType("bit");

                    b.Property<bool>("Propane_Tank_Status")
                        .HasColumnType("bit");

                    b.HasKey("FuelPropane_id");

                    b.ToTable("FuelPropane");
                });

            modelBuilder.Entity("LightningOffer.Models.HomeWarranty", b =>
                {
                    b.Property<Guid>("HomeWarranty_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Buyer_To_Pay_HW")
                        .HasColumnType("bit");

                    b.Property<bool>("Buyer_To_Purchase_HW_Later")
                        .HasColumnType("bit");

                    b.Property<bool>("Buyer_Waves_Right_To_HW")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HW")
                        .HasColumnType("bit");

                    b.Property<double>("HW_Price")
                        .HasColumnType("float");

                    b.Property<bool>("New_Construction_HW")
                        .HasColumnType("bit");

                    b.Property<bool>("Seller_To_Pay_HW")
                        .HasColumnType("bit");

                    b.HasKey("HomeWarranty_id");

                    b.ToTable("HomeWarranty");
                });

            modelBuilder.Entity("LightningOffer.Models.Inspection", b =>
                {
                    b.Property<Guid>("Inspection_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("As_Is")
                        .HasColumnType("bit");

                    b.Property<int>("Buyer_Inspection_Window")
                        .HasColumnType("int");

                    b.Property<bool>("Contingent_On_Survey")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Last_Best_Request_Window")
                        .HasColumnType("int");

                    b.Property<int>("Seller_Repair_Request_Response_Window")
                        .HasColumnType("int");

                    b.HasKey("Inspection_id");

                    b.ToTable("Inspection");
                });

            modelBuilder.Entity("LightningOffer.Models.Person", b =>
                {
                    b.Property<Guid>("Person_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ListAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListAgentPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListCompany")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Person_Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("LightningOffer.Models.Property", b =>
                {
                    b.Property<Guid>("Property_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlockNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeedBook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURLs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LotNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MlsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Page")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubLotNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Property_id");

                    b.ToTable("Property");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
