// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinningOffer.Data;

namespace WinningOffer.Migrations
{
    [DbContext(typeof(WinningOfferContext))]
    [Migration("20210515020111_updatesColumnNames")]
    partial class updatesColumnNames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WinningOffer.Models.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ARM_Limits")
                        .HasColumnType("int");

                    b.Property<bool>("Active_Lease")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("As_Is")
                        .HasColumnType("bit");

                    b.Property<string>("BlockNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Buyer_Appraisal_Required")
                        .HasColumnType("int");

                    b.Property<int>("Buyer_Inspection_Window")
                        .HasColumnType("int");

                    b.Property<string>("Buyer_Loan_Application_Start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Buyer_Title_Insurance")
                        .HasColumnType("bit");

                    b.Property<bool>("Buyer_To_Pay_HW")
                        .HasColumnType("bit");

                    b.Property<bool>("Buyer_To_Purchase_HW_Later")
                        .HasColumnType("bit");

                    b.Property<bool>("Buyer_Waives_Lead_Paint_Inspection")
                        .HasColumnType("bit");

                    b.Property<bool>("Buyer_Waves_Right_To_HW")
                        .HasColumnType("bit");

                    b.Property<bool>("Cash")
                        .HasColumnType("bit");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Closing_Window")
                        .HasColumnType("bit");

                    b.Property<bool>("Closing_Window_Latest")
                        .HasColumnType("bit");

                    b.Property<int>("Closing_Window_Soonest")
                        .HasColumnType("int");

                    b.Property<int>("ClothesDryer")
                        .HasColumnType("int");

                    b.Property<int>("ClothesWasher")
                        .HasColumnType("int");

                    b.Property<bool>("Contingent_Addendum")
                        .HasColumnType("bit");

                    b.Property<bool>("Contingent_On_Lead_Paint")
                        .HasColumnType("bit");

                    b.Property<bool>("Contingent_On_Survey")
                        .HasColumnType("bit");

                    b.Property<bool>("Conventional")
                        .HasColumnType("bit");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeedBook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Delayed_Possession_Addendum")
                        .HasColumnType("bit");

                    b.Property<int>("DishWasher")
                        .HasColumnType("int");

                    b.Property<int>("EMD")
                        .HasColumnType("int");

                    b.Property<bool>("EMD_With_ListingBroker")
                        .HasColumnType("bit");

                    b.Property<bool>("EMD_With_SellingBroker")
                        .HasColumnType("bit");

                    b.Property<bool>("FHA")
                        .HasColumnType("bit");

                    b.Property<bool>("Fixed_Rate")
                        .HasColumnType("bit");

                    b.Property<bool>("Gift")
                        .HasColumnType("bit");

                    b.Property<bool>("HOA_Addendum")
                        .HasColumnType("bit");

                    b.Property<bool>("HW")
                        .HasColumnType("bit");

                    b.Property<double>("HW_Price")
                        .HasColumnType("float");

                    b.Property<string>("ImageURLs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Interest_Rate")
                        .HasColumnType("int");

                    b.Property<DateTime>("Keys_after_Closing")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Keys_at_Closing")
                        .HasColumnType("bit");

                    b.Property<int>("Last_Best_Request_Window")
                        .HasColumnType("int");

                    b.Property<int>("Lead_Paint_Inspection_Window")
                        .HasColumnType("int");

                    b.Property<int>("Lender_Appraisal_Required")
                        .HasColumnType("int");

                    b.Property<bool>("LineOfEquity")
                        .HasColumnType("bit");

                    b.Property<string>("ListAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListAgentPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Loan_Length")
                        .HasColumnType("int");

                    b.Property<string>("LotNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Microwave")
                        .HasColumnType("int");

                    b.Property<string>("MlsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("New_Construction_HW")
                        .HasColumnType("bit");

                    b.Property<int>("No_Appraisal_Required")
                        .HasColumnType("int");

                    b.Property<bool>("No_Lead_Paint")
                        .HasColumnType("bit");

                    b.Property<int>("Other")
                        .HasColumnType("int");

                    b.Property<bool>("Other_Addendum")
                        .HasColumnType("bit");

                    b.Property<bool>("Other_Financing")
                        .HasColumnType("bit");

                    b.Property<string>("Other_Provisions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Page")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Propane_Leased")
                        .HasColumnType("bit");

                    b.Property<bool>("Propane_NotApplicable")
                        .HasColumnType("bit");

                    b.Property<bool>("Propane_NotRemain")
                        .HasColumnType("bit");

                    b.Property<bool>("Propane_Owned")
                        .HasColumnType("bit");

                    b.Property<bool>("Propane_Will_Remain")
                        .HasColumnType("bit");

                    b.Property<float>("Purchase_Price")
                        .HasColumnType("real");

                    b.Property<int>("Refrigerator")
                        .HasColumnType("int");

                    b.Property<bool>("Seller_Disclosure_Recieved")
                        .HasColumnType("bit");

                    b.Property<int>("Seller_Lead_Paint_Response_Window")
                        .HasColumnType("int");

                    b.Property<int>("Seller_Repair_Request_Response_Window")
                        .HasColumnType("int");

                    b.Property<bool>("Seller_To_Pay_HW")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Specific_Closing_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoveRange")
                        .HasColumnType("int");

                    b.Property<string>("SubLotNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VA")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Contract");
                });
#pragma warning restore 612, 618
        }
    }
}
