// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinningOffer.Data;

namespace WinningOffer.Migrations
{
    [DbContext(typeof(WinningOfferContext))]
    [Migration("20210520173708_dbupdateNoFK")]
    partial class dbupdateNoFK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WinningOffer.Models.Contract", b =>
                {
                    b.Property<Guid>("Contract_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BuyerSignedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ListAgentSignedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SellerSignedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SellingAgentSignedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Contract_id");

                    b.ToTable("Contract");
                });
#pragma warning restore 612, 618
        }
    }
}
